# Generated by Django 5.2.4 on 2025-07-27 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_shop_created_at_shop_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('change_type', models.CharField(choices=[('addition', 'Addition'), ('removal', 'Removal'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('transfer', 'Transfer'), ('initial_stock', 'Initial Stock')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='shop.shop')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_changes', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='inventory.product')),
            ],
        ),
    ]
