# Generated by Django 5.2.4 on 2025-07-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shop',
        ),
    ]
