# Generated by Django 5.2.4 on 2025-07-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_shop'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
