# Generated by Django 5.2.4 on 2025-07-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='shop',
            new_name='shop_id',
        ),
    ]
